### ISSUE TITLE
AI PRP: kestra RCE

### ISSUE THREAD

**Issue by lanced00m** [google/tsunami-security-scanner-plugins#605]
[Kestra](https://github.com/kestra-io/kestra) is a Workflow Automation Platform. Kestra is an alternative to Airflow and similar tools.

The default setup has no authentication mechanism, and when we set it up like:
```bash
docker run --pull=always --rm -it -p 8080:8080 --user=root \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp:/tmp kestra/kestra:latest server local
```
 We can create a Flow in many programming languages, including Shell scripts too:
```yaml
id: bash_single_command
namespace: company.team

tasks:
  - id: bash
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - 'echo "The current execution is : {{ execution.id }}"'

```

We can simply execute an out-of-band payload by sending two or three HTTP requests to a Kestra unauthenticated server.
